### ISSUE TITLE
API Content-Type is text/plain

### ISSUE THREAD

**Issue by Drusy** [Mxrk/tracker-poe#1]
Hi, 

API Content-Type is `text/plain` when should be `application/json` I guess.
Strict HTTP clients are rejecting requests when the header `Accept: application/json` is set.

```
curl -v \
	-H "User-Agent: PathOfExile/2.0 (fr.openium.poe; build:52; iOS 13.5.0) Alamofire/4.9.1" \
	-H "Accept-Language: en;q=1.0, fr-FR;q=0.9" \
	-H "Accept-Encoding: gzip" \
	-H "Accept: application/json" \
	"https://api.mrk.xyz/categories"
```

Request header: `Accept: application/json`
Response: `Content-Type: text/plain; charset=utf-8`

**Comment by Drusy** [comment]
@Mxrk https://api.mrk.xyz/categories seem to be working perfectly but I experience the same issue with https://api.mrk.xyz/get?category=map

Here is the curl

```
curl -v \
	-H "Accept-Language: en;q=1.0, fr-FR;q=0.9" \
	-H "User-Agent: PathOfExile/2.0 (fr.openium.poe; build:52; iOS 13.5.0) Alamofire/4.9.1" \
	-H "Accept-Encoding: gzip" \
	-H "Accept: application/json" \
	"https://api.mrk.xyz/get?category=map"
```

Request header: `Accept: application/json`
Response: `Content-Type: text/plain; charset=utf-8`

**Comment by Mxrk** [comment]
Hey, thanks for reporting. 👍 

Both endpoints should work now!
