### ISSUE TITLE
Kalandra end date wrong

### ISSUE THREAD

**Issue by Pegoth** [Mxrk/tracker-poe#10]
https://poe.watch/Leagues says that the end of the league is "20.8.2025 23:0:0UTC"

**Comment by Mxrk** [comment]
Hi, we don't know the current end date so this is the default placeholder. Or did you find something else?

**Comment by Pegoth** [comment]
Wouldn't it be better to be red and just add 3 months to the start (with a tooltip, that it is calculated)?

**Comment by Mxrk** [comment]
I can totally do that on the page. What do you think, should I include the day or just the month?

**Comment by Pegoth** [comment]
I think including the day is better, even if it is not accurate, easier to guess the next league that way.

**Comment by Mxrk** [comment]
Done!
