### ISSUE TITLE
Filter gemIsCorrupted is not working

### ISSUE THREAD

**Issue by jabaroid** [Mxrk/tracker-poe#11]
Filter "gemIsCorrupted" in URL is not working:
https://api.poe.watch/get?category=gem&league=Sanctum&gemIsCorrupted=false&gemLevel=20&name=Spark&gemQuality=20

It is not filtering corrupted gems.

**Comment by Mxrk** [comment]
Hi, your filtering isn't working because the correct query parameter is "gemCorrupted". Seems like I forgot the "Is" while writing the filter, thanks for noticing. 
I also have "gemCorrupted" in the filter docs, will add "gemIsCorrupted" with the next update! 

Sorry!

**Comment by Mxrk** [comment]
Now it should work, can you test it again?
