### ISSUE TITLE
Lifeforce prices are off

### ISSUE THREAD

**Issue by LinasKo** [Mxrk/tracker-poe#13]
Checking the prices for lifeforce, they're a bit odd. At the moment:
* Vivid is 8 Chaos
* Primal is 134
* Wild is 150.

Not a major need on my side, but if you do end up fixing it, leave a comment and I'll add the import button in [Gains of Exile](https://gains-of-exile.vercel.app/)

**Comment by Mxrk** [comment]
I can imagine why that’s the case, thanks for reporting.

**Comment by Mxrk** [comment]
Fixed the problem, will slowly come back.
Before the fix Primal was at 118 chaos, now it's at 0.05 chaos!
