### ISSUE TITLE
Specific items filter not working

### ISSUE THREAD

**Issue by Drusy** [Mxrk/tracker-poe#2]
Specific filter under the search bar don't work

For example:
The `Corrupted` and `Level` on https://stats.mrk.xyz/Gems or `Links` and `Types` for https://stats.mrk.xyz/Armour

Some filter are working, like the weapon links filters

**Comment by Mxrk** [comment]
Hey, thanks for reporting. Could you please check again? 
Uploaded a new version with fixed filters.

**Comment by Drusy** [comment]
Works like a charm, good job!
