### ISSUE TITLE
Feature request: Filter on get

### ISSUE THREAD

**Issue by C-Pettersson** [Mxrk/tracker-poe#5]
**Hello**
I would like a new feature on the gem API. However the feature could be implemented on all categories. 

**Problem description**
I want to pull data from your api, however the number of gems in standard has reached an ridiculous amount. Requests are taking quite some time.

**Suggested solution**
Allow us to apply filters on GET requests to the API. Preferably on "gemLevel", "gemQuality" & "gemIsCorrupted". Example:
`https://api.poe.watch/get?league=Ritual&category=gem&gemLevel=1`

**Alternative solution**
New parameter "limit" so we can limit the number of returned rows.
`https://api.poe.watch/get?league=Ritual&category=gem&limit=1000`

Kind regards,
C-Pettersson

**Comment by Mxrk** [comment]
Hey,
that is an awesome idea! 

I will add a possibilty for filtering on every get endpoint. But you said that the requests are taking some time, how long do they take for you?

**Comment by C-Pettersson** [comment]
> 
> 
> Hey,
> that is an awesome idea!
> 
> I will add a possibilty for filtering on every get endpoint. But you said that the requests are taking some time, how long do they take for you?

To be honest the request is pretty fast, but I'm consuming the API in google sheets which isn't that powerful. 4000+ gems can grind it to a halt.

**Comment by Mxrk** [comment]
Hey @C-Pettersson,

I added a basic filter function for the whole get endpoint, now you can filter for the following data:
"gemLevel", "gemCorrupted", "lowConfidence", "itemLevel", "linkCount".

So for your case:
`https://api.poe.watch/get?category=gem&league=Ritual&gemCorrupted=true`

Can you please check if it works like you imagined? If not, please tell me! Will add it to the docs after a bit more testing!

**Comment by C-Pettersson** [comment]
> 
> 
> Hey @C-Pettersson,
> 
> I added a basic filter function for the whole get endpoint, now you can filter for the following data:
> "gemLevel", "gemCorrupted", "lowConfidence", "itemLevel", "linkCount".
> 
> So for your case:
> `https://api.poe.watch/get?category=gem&league=Ritual&gemCorrupted=true`
> 
> Can you please check if it works like you imagined? If not, please tell me! Will add it to the docs after a bit more testing!

Lovely, I'll test it when I get home. thanks for the quick feature update :)

**Comment by C-Pettersson** [comment]
This works great. Thanks for the feature update :)
