### ISSUE TITLE
ritual league end time is incorrect

### ISSUE THREAD

**Issue by raylu** [Mxrk/tracker-poe#6]
https://www.pathofexile.com/forum/view-thread/3078209 says
> The Ritual League ends on PC on Monday April 12th at 2PM PDT,

**Comment by Mxrk** [comment]
Hey @raylu, appreciate it!
I should start checking for league endings more often, we had the same problem last league ... 
Will fix that!

**Comment by Mxrk** [comment]
The automatic update worked perfectly this time, should be working now for every league ending/starting.
Thanks again for reporting!
