### ISSUE TITLE
API Feature request: Fetch item by name

### ISSUE THREAD

**Issue by Davst** [Mxrk/tracker-poe#7]
Would be great to be able to fetch an item by name. I have a spreadsheet that would love to link to an item by building an url from the name i enter. searching by that name and picking up the item id and value would be much nicer than the alternative which as i understand would be to get all categories, then sift through each of them trying to find the item by name and catching this value.

**Comment by Mxrk** [comment]
Hey @Davst, appreciate the request.

I can totally add a filter by name function. If there are multiple hits it would return multiple items. Would that be the way you imagined? 

Like for example if you search "Queen of the Forest", you would find the 0,5,6 link item (except you would add more filters).

**Comment by Davst** [comment]
Yes, that sounds logical, hopefully the item variations are tagged.

A feature that'd be nice for me would be that all the components of the url would be available in the result, so I could build the hyperlink to the item as well (or of course the link being returned in the reply, but as long as there is a consistent schema to the urls that is buildable from thinks like category and id this feels slightly bloaty)

**Comment by Mxrk** [comment]
> Yes, that sounds logical, hopefully the item variations are tagged.

"tagged" that you see the differences? Sure, it's the normal object you are currently seeing. Or do you mean something else?


> A feature that'd be nice for me would be that all the components of the url would be available in the result, so I could build the hyperlink to the item as well

Could you please elaborate?

**Comment by Davst** [comment]
> Like for example if you search "Queen of the Forest", you would find the 0,5,6 link item (except you would add more filters).

In this example, that the 3 results would have a "links" property in the returning JSON so they could easily be told apart.

> A feature that'd be nice for me would be that all the components of the url would be available in the result, so I could build the hyperlink to the item as well

After looking at the item urls of your site this is kind of a non point. considering all the urls seem to be in the format /detailid/(id of item), but this being the case the URL is buildable as long as the item id is returned with the reply. (wasnt sure if some were /category/itemid or such in which case the category would have needed to be returned as well to build the url =))

**Comment by Mxrk** [comment]
I just added a new filter for the name property. Will update the docs later if it's working like intended for you.

`'get?league=Ultimatum&category=armour&name="Queen of the Forest"' ` will return all items now, where the name is "Queen of the Forest".
If you want to get more specific, you can use `'get?league=Ultimatum&category=armour&name="Queen of the Forest"&linkCount=6' `for example.

What do you think about that?
