### ISSUE TITLE
/corruption endpoint returns null

### ISSUE THREAD

**Issue by po0p** [Mxrk/tracker-poe#8]
https://api.poe.watch/corruptions endpoint seems to return null for me no matter what query parameters I use.

**Comment by Mxrk** [comment]
Hi, it's probably because the league is ending and the market isn't well used anymore.

For example the following ones still have some entries:

https://api.poe.watch/corruptions?id=1252&league=Standard
https://api.poe.watch/corruptions?id=1286&league=Sentinel

Or did I misinterpret your question?

**Comment by po0p** [comment]
A, alright, I thought they just out right don't work. Apparently they do. 
Its a bit irrelevant but could you please clarify how often market data is updated for sextants?

**Comment by Mxrk** [comment]
Depends on how active the league currently is, approximately every 30-60 minutes.
