### ISSUE TITLE
Question: Is there any way to match elder guardian maps?

### ISSUE THREAD

**Issue by Davst** [Mxrk/tracker-poe#9]
Looking to try to match elder guardian maps.. looked through the API and tried to find something that'd allow me to sort these.. didn't find much.. is there something I missed?

**Comment by Mxrk** [comment]
Hi, do you mean maps occupied by elder guardians?
If yes, no - there's no specific category for them. I don't differentiate currently but it is something I could add to the feature list.

**Comment by Davst** [comment]
Yeah I would definitely appriciate the possibility.. poe ninja can't do it at all

**Comment by po0p** [comment]
@Mxrk if you can do trade website requesting, here is overall search for elder maps:
`filters":[{"id":"implicit.stat_1792283443","value":{"option":2},"disabled":false}]`

**Comment by Mxrk** [comment]
I don't use the trade api because it's not intended for that usage. 
I am currently working on another feature and one fix, after that I will do the elder part. Will keep you updated here.

**Comment by Mxrk** [comment]
I am soon done with the rest and currently thinking about that feature: 

Every t14+ map has the possibility to get occupied by an Elder Guardian. That means each map would have 4 additional maps for each Guardian. 
Now I am thinking, would it better to have a separate category? I am currently unsure because we would get a ton of new items. 

Another possibility would be to have something like "T14 Map occupied by ...". 
With that there would only be 4 new items per tier, which means 4*3 because t14, t15 and t16.
Most occupied maps seems like to have the same price(?).

**Comment by Davst** [comment]
For me. 

The original case i was looking for was some way to price elder maps.. since poe.ninja just takes a map with a random icon.. so what I was looking for was to:

1. Look for any Eradicator Map (also of tier X)
2. Look for Elder say.. Mesa maps in particular
3. Be able to pull data for ROI calculations. So for me.. as long as you can see a specific map.. (sometimes influenced maps of a particular kind are more valuable than others) and see what influence it had I'd be happy

**Comment by Mxrk** [comment]
> For me.
> 
> The original case i was looking for was some way to price elder maps.. since poe.ninja just takes a map with a random icon.. so what I was looking for was to:
> 
>     1. Look for any Eradicator Map (also of tier X)
> 
>     2. Look for Elder say.. Mesa maps in particular
> 
>     3. Be able to pull data for ROI calculations. So for me.. as long as you can see a specific map.. (sometimes influenced maps of a particular kind are more valuable than others) and see what influence it had I'd be happy

It's a really late reply but I came back to that topic. I basically rewrote the whole pricing part so now I can think about new items.

Wouldn't that also work if we have one item per elder and tier?
There shouldn't be a price difference between the maps as the fragment is carrying the price.

**Comment by Mxrk** [comment]
You can now find them in the map section!
